from enum import StrEnum


class ErrorCode(StrEnum):
    INTERNAL_ERROR = "INTERNAL_ERROR"
    VALIDATION_ERROR = "VALIDATION_ERROR"
    NOT_FOUND = "NOT_FOUND"
    CONFLICT = "CONFLICT"
    AUTH_INVALID_CREDENTIALS = "AUTH_INVALID_CREDENTIALS"
    AUTH_INVALID_TOKEN = "AUTH_INVALID_TOKEN"
    AUTH_TOKEN_EXPIRED = "AUTH_TOKEN_EXPIRED"
    AUTH_TOKEN_REVOKED = "AUTH_TOKEN_REVOKED"
    AUTH_TOKEN_REUSE_DETECTED = "AUTH_TOKEN_REUSE_DETECTED"
    AUTH_INACTIVE_USER = "AUTH_INACTIVE_USER"
    AUTH_EMAIL_EXISTS = "AUTH_EMAIL_EXISTS"
    AUTH_USERNAME_EXISTS = "AUTH_USERNAME_EXISTS"
    AUTH_FORBIDDEN = "AUTH_FORBIDDEN"
    LLM_PROVIDER_NOT_FOUND = "LLM_PROVIDER_NOT_FOUND"
    LLM_PROVIDER_ERROR = "LLM_PROVIDER_ERROR"
    LLM_NOT_CONFIGURED = "LLM_NOT_CONFIGURED"
